### ISSUE TITLE
Apple Silicon issues

### ISSUE THREAD

**Issue by mattloose** [Adoni5/mappy-rs#38]
Compiling on Apple Silicon seems impossible.

Error messages are:

  error occurred: Command "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-arch" "arm64" "-static" "-I" "minimap2" "-Wc++-compat" "-DHAVE_KALLOC" "-lm" "-lpthread" "-o" "/Users/mattloose/GIT/mappy-rs/target/debug/build/minimap2-sys-a801728ffb604384/out/minimap2/ksw2_ll_sse.o" "-c" "minimap2/ksw2_ll_sse.c" with args "cc" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...

**Comment by alexomics** [comment]
Build it using an x86-64, this is easiest using conda. Python 3.9 is not a hard requirement here, just illustrative.

_env.yml_
```yaml
name: mappy_rs_x86
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - maturin
```

Then create the environment:

```console
CONDA_SUBDIR=osx-64 conda env create -f env.yml
conda activate mappy_rs_x86
```

Build your wheel, this needs to happen with the conda env activated:

```console
git clone https://github.com/Adoni5/mappy-rs
cd mappy-rs
maturin build --target x86_64-apple-darwin --release --out dist --interpreter 3.9
```

Install the wheel:

```console
pip install dist/mappy_rs-0.0.3-cp39-cp39-macosx_10_7_x86_64.whl
```

Now test it:

```console
pip install pytest
pytest -v tests/python_test.py && python -c 'import platform; print(platform.platform()); import mappy_rs'
```

**Comment by Adoni5** [comment]
From what I was reading yesterday, there should be no issue in building on Apple silicon, if we do it correctly. The problem @mattloose had was we have no target for arm-darwin-X, but as I have literally no way to work on this 🤷🏼‍♂️ 

I tried building on my raspberry pi 3 (armv7, 7 years old) but it basically burst into flames and crashed!
